language: python
python:
  - "2.7"
# command to install dependencies
install:
  # Install conda
  - sudo pip install conda
  # install deps
  - sudo conda init
  # sudo conda update conda --yes
  - conda create -p $HOME/py --yes pip numpy scipy scikit-learn "python=$TRAVIS_PYTHON_VERSION"
  - export PATH=$HOME/py/bin:$PATH
  # command to install dependencies
  - pip install unidecode nltk
  - pip install coveralls
  - python2.7 -c "import nltk; nltk.download('stopwords'); nltk.download('punkt')"
  - python setup.py develop
# command to run tests
before_script: pip install unittest2 nose
script: coverage run --source vsm setup.py test
after_success: coveralls
