language: python
python:
  - "2.7"
# command to install dependencies
install:
  # Install conda
  - if [[ "$TRAVIS_PYTHON_VERSION" == "2.7" ]]; then
      wget https://repo.continuum.io/miniconda/Miniconda-latest-Linux-x86_64.sh -O miniconda.sh;
    else
      wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
    fi
  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"
  - hash -r
  - conda config --set always_yes yes --set changeps1 no
  - conda update -q conda --yes
  - conda create -n py -q --yes pip numpy scipy scikit-learn unidecode nltk futures chardet cython "python=$TRAVIS_PYTHON_VERSION"
  - source activate py
  - python --version
  - pip --version
  # command to install dependencies
  - pip install coveralls
  - python -c "import nltk; nltk.download('stopwords'); nltk.download('punkt')"
  - pip install . -i https://inpho.cogs.indiana.edu/pypi
# command to run tests
before_script: 
  - pip install unittest2 nose
script: coverage run --source vsm.model,vsm.viewer,vsm.corpus,vsm.spatial,vsm.split,vsm.structarr,vsm.exceptions setup.py test
after_success: coveralls
